/**
 * Laravel documentation sections mapped to Strata public APIs and test coverage.
 * Ecosystem tier is reserved for optional Laravel-package exclusions not shipped in Strata.
 */

export type ParityTier = "core" | "ecosystem";

export interface ParityEntry {
  id: string;
  laravelSection: string;
  laravelDocPath: string;
  strataApis: string[];
  bootstrapApis?: string[];
  testGlobs: string[];
  tier: ParityTier;
  notes?: string;
}

/** Laravel doc sections → Strata API → tests. */
export const PARITY_CATALOG: ParityEntry[] = [
  {
    id: "service-container",
    laravelSection: "Service Container",
    laravelDocPath: "container",
    strataApis: ["ServiceContainer", "resolveService"],
    bootstrapApis: ["ServiceContainer", "resolveService"],
    testGlobs: ["unit/providers.test.ts"],
    tier: "core",
  },
  {
    id: "service-providers",
    laravelSection: "Service Providers",
    laravelDocPath: "providers",
    strataApis: [],
    bootstrapApis: ["ServiceProvider", "runProviderPhase", "collectProviders", "createAppContext"],
    testGlobs: ["unit/providers.test.ts", "unit/discoverModules.test.ts"],
    tier: "core",
  },
  {
    id: "facades",
    laravelSection: "Facades",
    laravelDocPath: "facades",
    strataApis: [
      "cache",
      "queue",
      "events",
      "auth",
      "config",
      "log",
      "mail",
      "storage",
      "policyGate",
    ],
    testGlobs: ["unit/events.test.ts", "unit/cacheRepository.test.ts"],
    tier: "core",
  },
  {
    id: "routing",
    laravelSection: "Routing",
    laravelDocPath: "routing",
    strataApis: ["applyMiddlewareToRoutes", "withMiddleware", "composeMiddleware"],
    bootstrapApis: ["createHttpKernel", "createWebRoutes"],
    testGlobs: ["unit/httpKernel.test.ts", "unit/routeMiddlewareGroups.test.ts"],
    tier: "core",
  },
  {
    id: "middleware",
    laravelSection: "Middleware",
    laravelDocPath: "middleware",
    strataApis: [
      "createCsrfMiddleware",
      "createSecurityHeadersMiddleware",
      "createBodySizeLimitMiddleware",
      "createAuthMiddleware",
      "createAuthorizeMiddleware",
    ],
    testGlobs: ["unit/csrf.test.ts", "unit/middleware.test.ts"],
    tier: "core",
  },
  {
    id: "csrf",
    laravelSection: "CSRF Protection",
    laravelDocPath: "csrf",
    strataApis: ["createCsrfMiddleware"],
    bootstrapApis: ["createCsrfProtection"],
    testGlobs: ["unit/csrf.test.ts"],
    tier: "core",
  },
  {
    id: "controllers",
    laravelSection: "Controllers",
    laravelDocPath: "controllers",
    strataApis: ["withErrorHandling", "jsonResponse", "RouteHandler"],
    testGlobs: ["integration/routes.integration.test.ts"],
    tier: "core",
  },
  {
    id: "form-requests",
    laravelSection: "Form Requests",
    laravelDocPath: "validation#form-request-validation",
    strataApis: ["FormRequest", "WebFormRequest", "validateObject", "required", "emailRule"],
    testGlobs: [
      "unit/formRequest.test.ts",
      "unit/webFormRequest.test.ts",
      "unit/validationRules.test.ts",
    ],
    tier: "core",
  },
  {
    id: "views",
    laravelSection: "Views",
    laravelDocPath: "views",
    strataApis: ["EtaViewEngine", "htmlResponse", "resolveWebLayoutData"],
    testGlobs: ["unit/etaViewEngine.test.ts", "unit/webLayoutData.test.ts"],
    tier: "core",
  },
  {
    id: "validation",
    laravelSection: "Validation",
    laravelDocPath: "validation",
    strataApis: ["ValidationError", "validateObject", "minLength", "maxLength", "stringRule"],
    testGlobs: ["unit/validationRules.test.ts", "unit/httpValidation.test.ts"],
    tier: "core",
  },
  {
    id: "errors",
    laravelSection: "Error Handling",
    laravelDocPath: "errors",
    strataApis: ["NotFoundError", "ForbiddenError", "UnauthorizedError", "BadRequestError"],
    testGlobs: ["unit/databaseErrors.test.ts"],
    tier: "core",
  },
  {
    id: "database",
    laravelSection: "Database: Getting Started",
    laravelDocPath: "database",
    strataApis: [
      "bindDatabaseConnection",
      "getActiveDatabaseConnection",
      "runWithDatabaseConnection",
    ],
    testGlobs: ["unit/databaseConnection.test.ts", "unit/database.test.ts"],
    tier: "core",
  },
  {
    id: "query-builder",
    laravelSection: "Query Builder",
    laravelDocPath: "queries",
    strataApis: ["RepositoryQuery", "WhereBuilder", "BaseRepository"],
    testGlobs: ["unit/database/queryBuilder.test.ts", "unit/repositoryQuery.test.ts"],
    tier: "core",
  },
  {
    id: "pagination",
    laravelSection: "Pagination",
    laravelDocPath: "pagination",
    strataApis: ["paginatedResponse", "parsePaginationQuery", "toPaginatedResourceCollection"],
    testGlobs: ["unit/pagination.test.ts"],
    tier: "core",
  },
  {
    id: "migrations",
    laravelSection: "Migrations",
    laravelDocPath: "migrations",
    strataApis: [
      "migrateDatabase",
      "rollbackDatabase",
      "freshDatabase",
      "loadMigrationsFromDirectory",
      "withMigrationLock",
    ],
    testGlobs: ["unit/migrationRunner.test.ts"],
    tier: "core",
  },
  {
    id: "schema-blueprint",
    laravelSection: "Schema Builder",
    laravelDocPath: "migrations#tables",
    strataApis: ["Schema", "Blueprint", "defineTable", "createSchemaBuilder", "PostgresGrammar"],
    testGlobs: ["unit/database/schema/grammarSnapshots.test.ts"],
    tier: "core",
  },
  {
    id: "seeders",
    laravelSection: "Database Seeding",
    laravelDocPath: "seeding",
    strataApis: ["runSeedersFromDirectory", "loadSeedersFromDirectory"],
    testGlobs: ["unit/frameworkPublicApi.test.ts"],
    tier: "core",
  },
  {
    id: "eloquent-model",
    laravelSection: "Eloquent: Getting Started",
    laravelDocPath: "eloquent",
    strataApis: [
      "Model",
      "registerModelRepository",
      "filterMassAssignable",
      "hydrateValue",
      "applyCasts",
    ],
    testGlobs: ["unit/database/model.test.ts", "unit/model.test.ts"],
    tier: "core",
  },
  {
    id: "eloquent-relationships",
    laravelSection: "Eloquent: Relationships",
    laravelDocPath: "eloquent-relationships",
    strataApis: ["hasMany", "hasOne", "belongsTo", "belongsToMany", "indexHasManyRelation"],
    testGlobs: ["unit/database/model.relationships.test.ts", "unit/belongsTo.test.ts"],
    tier: "core",
  },
  {
    id: "eloquent-soft-deletes",
    laravelSection: "Eloquent: Soft Deleting",
    laravelDocPath: "eloquent#soft-deleting",
    strataApis: ["Model"],
    testGlobs: ["unit/database/model.softDelete.test.ts", "unit/softDeletes.test.ts"],
    tier: "core",
  },
  {
    id: "api-resources",
    laravelSection: "Eloquent: API Resources",
    laravelDocPath: "eloquent-resources",
    strataApis: ["toResourceCollection", "serializeDate", "toPaginatedResourceCollection"],
    testGlobs: ["unit/frameworkPublicApi.test.ts", "unit/presentation.test.ts"],
    tier: "core",
  },
  {
    id: "factories",
    laravelSection: "Eloquent: Factories",
    laravelDocPath: "eloquent-factories",
    strataApis: [],
    testGlobs: ["unit/factory.test.ts"],
    tier: "core",
    notes: "Exported via @getstrata/core/database/factory subpath",
  },
  {
    id: "authorization",
    laravelSection: "Authorization",
    laravelDocPath: "authorization",
    strataApis: ["Policy", "PolicyGate", "createAuthorizeMiddleware"],
    testGlobs: ["unit/policy.test.ts", "unit/policyGate.test.ts"],
    tier: "core",
  },
  {
    id: "authentication",
    laravelSection: "Authentication",
    laravelDocPath: "authentication",
    strataApis: ["createAuthMiddleware", "createRequireAuthMiddleware", "currentAuthUser"],
    testGlobs: ["unit/authService.test.ts", "unit/authMiddleware.test.ts"],
    tier: "core",
  },
  {
    id: "route-model-binding",
    laravelSection: "Route Model Binding",
    laravelDocPath: "routing#route-model-binding",
    strataApis: ["securedBindRouteModel", "securedBindRouteModelByKey"],
    bootstrapApis: ["securedBindRouteModel", "securedBindRouteModelByKey"],
    testGlobs: ["unit/securedRouteModelBinding.test.ts", "unit/securedRouteModelByKey.test.ts"],
    tier: "core",
  },
  {
    id: "events",
    laravelSection: "Events",
    laravelDocPath: "events",
    strataApis: ["EventBus", "events"],
    testGlobs: ["unit/events.test.ts"],
    tier: "core",
  },
  {
    id: "queues",
    laravelSection: "Queues",
    laravelDocPath: "queues",
    strataApis: [
      "Job",
      "RedisQueue",
      "QueueWorker",
      "jobRegistry",
      "createProductionQueue",
      "SyncQueue",
    ],
    bootstrapApis: ["registerDefaultJobs"],
    testGlobs: [
      "unit/queue.test.ts",
      "unit/redisQueue.test.ts",
      "integration/queue.integration.test.ts",
    ],
    tier: "core",
  },
  {
    id: "failed-jobs",
    laravelSection: "Queues: Dealing With Failed Jobs",
    laravelDocPath: "queues#dealing-with-failed-jobs",
    strataApis: ["FailedJobService", "FailedJobRepository", "createFailedJobService"],
    testGlobs: ["unit/failedJobService.test.ts"],
    tier: "core",
  },
  {
    id: "scheduler",
    laravelSection: "Task Scheduling",
    laravelDocPath: "scheduling",
    strataApis: ["Schedule", "appSchedule", "runDueScheduledTasks"],
    bootstrapApis: ["scheduleRunCommand"],
    testGlobs: ["unit/schedule.test.ts", "unit/bootstrapSchedule.test.ts"],
    tier: "core",
  },
  {
    id: "cache",
    laravelSection: "Cache",
    laravelDocPath: "cache",
    strataApis: [
      "CacheRepository",
      "CACHE_TAGS",
      "cacheTagsForModelWrite",
      "discoverModelTableNames",
    ],
    bootstrapApis: ["cacheTagsForModelWrite", "discoverModelTableNames"],
    testGlobs: ["unit/cacheRepository.test.ts", "unit/modelCacheTags.test.ts"],
    tier: "core",
  },
  {
    id: "rate-limiting",
    laravelSection: "Rate Limiting",
    laravelDocPath: "routing#rate-limiting",
    strataApis: [
      "createThrottleMiddleware",
      "createMemoryThrottleMiddleware",
      "createLoginThrottleMiddleware",
    ],
    testGlobs: ["unit/throttleMiddleware.test.ts", "unit/memoryThrottleMiddleware.test.ts"],
    tier: "core",
  },
  {
    id: "file-storage",
    laravelSection: "File Storage",
    laravelDocPath: "filesystem",
    strataApis: ["StorageManager", "LocalStorageDriver", "storage"],
    testGlobs: ["unit/storage.test.ts"],
    tier: "core",
  },
  {
    id: "mail",
    laravelSection: "Mail",
    laravelDocPath: "mail",
    strataApis: ["Mailer", "LogMailDriver", "mailer", "mail"],
    testGlobs: ["unit/mailer.test.ts"],
    tier: "core",
  },
  {
    id: "transactions",
    laravelSection: "Database: Transactions",
    laravelDocPath: "database#database-transactions",
    strataApis: ["runInTransaction"],
    testGlobs: ["unit/database.test.ts"],
    tier: "core",
  },
  {
    id: "graceful-shutdown",
    laravelSection: "Deployment: Graceful Shutdown",
    laravelDocPath: "deployment",
    strataApis: [
      "installGracefulShutdownSignals",
      "registerShutdownHandler",
      "runGracefulShutdown",
    ],
    testGlobs: ["unit/gracefulShutdown.test.ts"],
    tier: "core",
  },
  {
    id: "metrics",
    laravelSection: "Observability",
    laravelDocPath: "logging",
    strataApis: ["PrometheusRegistry", "prometheusRegistry", "createMetricsMiddleware"],
    testGlobs: ["unit/metrics.test.ts", "unit/metricsRoutes.test.ts"],
    tier: "core",
  },
  {
    id: "etag",
    laravelSection: "HTTP: Conditional Requests",
    laravelDocPath: "requests",
    strataApis: ["assertIfMatch", "etagFromResource", "isEtagEnabled"],
    testGlobs: ["unit/etag.test.ts"],
    tier: "core",
  },
  {
    id: "web-session",
    laravelSection: "Session",
    laravelDocPath: "session",
    strataApis: [],
    bootstrapApis: ["CookieSessionStore", "createWebServer"],
    testGlobs: ["unit/sessionCookie.test.ts", "unit/flashSession.test.ts"],
    tier: "core",
  },
  {
    id: "chunk-cursor",
    laravelSection: "Query Builder: Chunks / Cursors",
    laravelDocPath: "queries#chunking-results",
    strataApis: ["BaseRepository"],
    testGlobs: ["unit/database/repositoryPhase3.test.ts"],
    tier: "core",
    notes: "chunk() and cursorPaginate() on BaseRepository",
  },
  {
    id: "stripe-webhooks",
    laravelSection: "Billing Webhooks",
    laravelDocPath: "billing",
    strataApis: [],
    testGlobs: ["unit/stripeWebhook.test.ts"],
    tier: "core",
    notes: "verifyStripeWebhook via @getstrata/core/security/stripeWebhook subpath",
  },
  {
    id: "morph-relations",
    laravelSection: "Eloquent: Polymorphic Relations",
    laravelDocPath: "eloquent-relationships#polymorphic-relationships",
    strataApis: [
      "morphTo",
      "morphMany",
      "morphOne",
      "indexMorphManyRelation",
      "indexMorphOneRelation",
      "indexMorphToRelation",
    ],
    testGlobs: ["unit/database/morphRelations.test.ts", "unit/repositoryQuery.test.ts"],
    tier: "core",
  },
  {
    id: "notifications",
    laravelSection: "Notifications",
    laravelDocPath: "notifications",
    strataApis: ["Notification", "NotificationDispatcher", "createNotificationDispatcher"],
    testGlobs: ["unit/notifications.test.ts"],
    tier: "core",
    notes: "Mail and database channels; Slack/SMS remain app-level integrations",
  },
  {
    id: "mail-markdown",
    laravelSection: "Mail: Markdown Templates",
    laravelDocPath: "mail#markdown-mailables",
    strataApis: [
      "renderMarkdownMail",
      "buildMarkdownMailMessage",
      "sendMarkdownMail",
      "markdownToHtml",
    ],
    testGlobs: ["unit/markdownMail.test.ts", "unit/mailer.test.ts"],
    tier: "core",
  },
  {
    id: "horizon",
    laravelSection: "Horizon (queue dashboard)",
    laravelDocPath: "horizon",
    strataApis: [
      "collectQueueMetrics",
      "FailedJobService",
      "FailedJobRepository",
      "createFailedJobService",
    ],
    testGlobs: [
      "unit/adminServiceMetrics.test.ts",
      "unit/adminService.test.ts",
      "integration/webRoutes.integration.test.ts",
    ],
    tier: "core",
    notes: "Horizon-lite admin queue monitor at /admin/queue with HTMX polling, retry, and delete",
  },
  {
    id: "nova",
    laravelSection: "Nova (admin panel)",
    laravelDocPath: "nova",
    strataApis: ["AdminResourceRegistry", "formatAdminValue"],
    testGlobs: [
      "unit/adminRegistry.test.ts",
      "unit/adminService.test.ts",
      "integration/webRoutes.integration.test.ts",
    ],
    tier: "core",
    notes: "WorkHub admin module with resource browser at /admin/resources",
  },
  {
    id: "cli",
    laravelSection: "Artisan Console",
    laravelDocPath: "artisan",
    strataApis: [],
    bootstrapApis: ["scheduleRunCommand"],
    testGlobs: ["unit/bootstrapSchedule.test.ts"],
    tier: "core",
    notes: "@getstrata/cli — migrate, queue:work, make:* generators",
  },
];
