const APP_PORT_CONFIG_KEY = "app.port";
const CACHE_TTL_MS_CONFIG_KEY = "cache.ttlMs";
const CACHE_MAX_ENTRIES_CONFIG_KEY = "cache.maxEntries";

const CORE_CONFIG_TOKEN = "core.config";
const CORE_CACHE_TOKEN = "core.cache";

const DEFAULT_APP_PORT = 3000;
const DEFAULT_CACHE_TTL_MS = 3_600_000;
const DEFAULT_CACHE_MAX_ENTRIES = 100;

export {
  APP_PORT_CONFIG_KEY,
  CACHE_MAX_ENTRIES_CONFIG_KEY,
  CACHE_TTL_MS_CONFIG_KEY,
  CORE_CACHE_TOKEN,
  CORE_CONFIG_TOKEN,
  DEFAULT_APP_PORT,
  DEFAULT_CACHE_MAX_ENTRIES,
  DEFAULT_CACHE_TTL_MS,
};
