const APP_PORT_CONFIG_KEY = "app.port";
const CACHE_TTL_MS_CONFIG_KEY = "cache.ttlMs";
const CACHE_MAX_ENTRIES_CONFIG_KEY = "cache.maxEntries";
const CACHE_DRIVER_CONFIG_KEY = "cache.driver";
const REDIS_URL_CONFIG_KEY = "cache.redisUrl";
const DATABASE_URL_CONFIG_KEY = "database.url";

export {
  CORE_ABILITY_CHECKER_TOKEN,
  CORE_AUTH_TOKEN,
  CORE_AUTH_USER_DIRECTORY_TOKEN,
  CORE_CACHE_TOKEN,
  CORE_CONFIG_TOKEN,
  CORE_EVENT_BUS_TOKEN,
  CORE_POLICY_GATE_TOKEN,
  CORE_QUEUE_TOKEN,
  CORE_TOKEN_SERVICE_TOKEN,
} from "@getstrata/core/contracts/serviceTokens";

const AUTH_DEV_HEADERS_CONFIG_KEY = "auth.allowDevHeaders";

const DEFAULT_APP_PORT = 3000;
const DEFAULT_CACHE_TTL_MS = 3_600_000;
const DEFAULT_CACHE_MAX_ENTRIES = 100;
const DEFAULT_CACHE_DRIVER = "array";
const DEFAULT_API_TOKEN = "";
const DEFAULT_QUEUE_DRIVER = "sync";

export {
  APP_PORT_CONFIG_KEY,
  AUTH_DEV_HEADERS_CONFIG_KEY,
  CACHE_DRIVER_CONFIG_KEY,
  CACHE_MAX_ENTRIES_CONFIG_KEY,
  CACHE_TTL_MS_CONFIG_KEY,
  DATABASE_URL_CONFIG_KEY,
  DEFAULT_API_TOKEN,
  DEFAULT_APP_PORT,
  DEFAULT_CACHE_DRIVER,
  DEFAULT_CACHE_MAX_ENTRIES,
  DEFAULT_CACHE_TTL_MS,
  DEFAULT_QUEUE_DRIVER,
  REDIS_URL_CONFIG_KEY,
};
